services:
  db:
    image: postgres@sha256:c62fdb7fd6f519ef425c54760894c74e8d0cb04fbf4f7d3d79aafd86bae24edd
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: gtnh_2_6_1
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - gtnh-recipes:/var/lib/postgresql/data

volumes:
  gtnh-recipes:
