version: "3"

tasks:
  build:
    cmds:
      - go generate ./ent
      - templ generate
      - go build -o backend cmd/backend/main.go
    sources:
      - "**/*.go"
      - "**/*.templ"
      - exclude: "**/*_templ.go"
      - exclude: "ent/**/*.go"
      - "ent/schema/*.go"
    generates:
      - backend
  db:
    cmds:
      - docker compose exec db psql -U postgres -d gtnh_2_6_1
  db-log:
    cmds:
      - docker compose logs --tail=100 -f
  run:
    deps: [build]
    cmds:
      - ./backend
  test:
    cmds:
      - go test ./...
    sources:
      - "**/*.go"
      - exclude: "components/**/*"
      - exclude: "ent/migrate/**/*.go"
      - exclude: "ent/schema/*.go" # These are inputs for ent codegen and can be ignored for tests
