version: "3"

tasks:
  build:
    cmds:
      - templ generate
      - go build -o backend cmd/backend/main.go
    sources:
      - "**/*.go"
      - "**/*.templ"
      - exclude: "**/*_templ.go"
    generates:
      - backend
  db:
    cmds:
      - docker compose exec db psql -U postgres -d gtnh_recipes
  run:
    deps: [build]
    cmds:
      - ./backend
