// Code generated by ent, DO NOT EDIT.

package recipe

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the recipe type in the database.
	Label = "recipe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRecipeTypeID holds the string denoting the recipe_type_id field in the database.
	FieldRecipeTypeID = "recipe_type_id"
	// EdgeRecipeType holds the string denoting the recipe_type edge name in mutations.
	EdgeRecipeType = "recipe_type"
	// Table holds the table name of the recipe in the database.
	Table = "recipe"
	// RecipeTypeTable is the table that holds the recipe_type relation/edge.
	RecipeTypeTable = "recipe"
	// RecipeTypeInverseTable is the table name for the RecipeType entity.
	// It exists in this package in order to avoid circular dependency with the "recipetype" package.
	RecipeTypeInverseTable = "recipe_type"
	// RecipeTypeColumn is the table column denoting the recipe_type relation/edge.
	RecipeTypeColumn = "recipe_type_id"
)

// Columns holds all SQL columns for recipe fields.
var Columns = []string{
	FieldID,
	FieldRecipeTypeID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Recipe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRecipeTypeID orders the results by the recipe_type_id field.
func ByRecipeTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipeTypeID, opts...).ToFunc()
}

// ByRecipeTypeField orders the results by recipe_type field.
func ByRecipeTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecipeTypeStep(), sql.OrderByField(field, opts...))
	}
}
func newRecipeTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecipeTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RecipeTypeTable, RecipeTypeColumn),
	)
}
