// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevinkjt2000/factory-planner/ent/predicate"
	"github.com/kevinkjt2000/factory-planner/ent/recipeitemoutputs"
)

// RecipeItemOutputsUpdate is the builder for updating RecipeItemOutputs entities.
type RecipeItemOutputsUpdate struct {
	config
	hooks    []Hook
	mutation *RecipeItemOutputsMutation
}

// Where appends a list predicates to the RecipeItemOutputsUpdate builder.
func (riou *RecipeItemOutputsUpdate) Where(ps ...predicate.RecipeItemOutputs) *RecipeItemOutputsUpdate {
	riou.mutation.Where(ps...)
	return riou
}

// Mutation returns the RecipeItemOutputsMutation object of the builder.
func (riou *RecipeItemOutputsUpdate) Mutation() *RecipeItemOutputsMutation {
	return riou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (riou *RecipeItemOutputsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, riou.sqlSave, riou.mutation, riou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (riou *RecipeItemOutputsUpdate) SaveX(ctx context.Context) int {
	affected, err := riou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (riou *RecipeItemOutputsUpdate) Exec(ctx context.Context) error {
	_, err := riou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riou *RecipeItemOutputsUpdate) ExecX(ctx context.Context) {
	if err := riou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riou *RecipeItemOutputsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipeitemoutputs.Table, recipeitemoutputs.Columns, sqlgraph.NewFieldSpec(recipeitemoutputs.FieldID, field.TypeInt))
	if ps := riou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, riou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipeitemoutputs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	riou.mutation.done = true
	return n, nil
}

// RecipeItemOutputsUpdateOne is the builder for updating a single RecipeItemOutputs entity.
type RecipeItemOutputsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecipeItemOutputsMutation
}

// Mutation returns the RecipeItemOutputsMutation object of the builder.
func (riouo *RecipeItemOutputsUpdateOne) Mutation() *RecipeItemOutputsMutation {
	return riouo.mutation
}

// Where appends a list predicates to the RecipeItemOutputsUpdate builder.
func (riouo *RecipeItemOutputsUpdateOne) Where(ps ...predicate.RecipeItemOutputs) *RecipeItemOutputsUpdateOne {
	riouo.mutation.Where(ps...)
	return riouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (riouo *RecipeItemOutputsUpdateOne) Select(field string, fields ...string) *RecipeItemOutputsUpdateOne {
	riouo.fields = append([]string{field}, fields...)
	return riouo
}

// Save executes the query and returns the updated RecipeItemOutputs entity.
func (riouo *RecipeItemOutputsUpdateOne) Save(ctx context.Context) (*RecipeItemOutputs, error) {
	return withHooks(ctx, riouo.sqlSave, riouo.mutation, riouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (riouo *RecipeItemOutputsUpdateOne) SaveX(ctx context.Context) *RecipeItemOutputs {
	node, err := riouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (riouo *RecipeItemOutputsUpdateOne) Exec(ctx context.Context) error {
	_, err := riouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riouo *RecipeItemOutputsUpdateOne) ExecX(ctx context.Context) {
	if err := riouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riouo *RecipeItemOutputsUpdateOne) sqlSave(ctx context.Context) (_node *RecipeItemOutputs, err error) {
	_spec := sqlgraph.NewUpdateSpec(recipeitemoutputs.Table, recipeitemoutputs.Columns, sqlgraph.NewFieldSpec(recipeitemoutputs.FieldID, field.TypeInt))
	id, ok := riouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecipeItemOutputs.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := riouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recipeitemoutputs.FieldID)
		for _, f := range fields {
			if !recipeitemoutputs.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recipeitemoutputs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := riouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &RecipeItemOutputs{config: riouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, riouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recipeitemoutputs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	riouo.mutation.done = true
	return _node, nil
}
