// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kevinkjt2000/factory-planner/ent/recipeitemoutputs"
)

// RecipeItemOutputs is the model entity for the RecipeItemOutputs schema.
type RecipeItemOutputs struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecipeItemOutputs) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recipeitemoutputs.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecipeItemOutputs fields.
func (rio *RecipeItemOutputs) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recipeitemoutputs.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rio.ID = int(value.Int64)
		default:
			rio.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecipeItemOutputs.
// This includes values selected through modifiers, order, etc.
func (rio *RecipeItemOutputs) Value(name string) (ent.Value, error) {
	return rio.selectValues.Get(name)
}

// Update returns a builder for updating this RecipeItemOutputs.
// Note that you need to call RecipeItemOutputs.Unwrap() before calling this method if this RecipeItemOutputs
// was returned from a transaction, and the transaction was committed or rolled back.
func (rio *RecipeItemOutputs) Update() *RecipeItemOutputsUpdateOne {
	return NewRecipeItemOutputsClient(rio.config).UpdateOne(rio)
}

// Unwrap unwraps the RecipeItemOutputs entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rio *RecipeItemOutputs) Unwrap() *RecipeItemOutputs {
	_tx, ok := rio.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecipeItemOutputs is not a transactional entity")
	}
	rio.config.driver = _tx.drv
	return rio
}

// String implements the fmt.Stringer.
func (rio *RecipeItemOutputs) String() string {
	var builder strings.Builder
	builder.WriteString("RecipeItemOutputs(")
	builder.WriteString(fmt.Sprintf("id=%v", rio.ID))
	builder.WriteByte(')')
	return builder.String()
}

// RecipeItemOutputsSlice is a parsable slice of RecipeItemOutputs.
type RecipeItemOutputsSlice []*RecipeItemOutputs
