// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Recipe is the predicate function for recipe builders.
type Recipe func(*sql.Selector)

// RecipeItemOutputs is the predicate function for recipeitemoutputs builders.
type RecipeItemOutputs func(*sql.Selector)

// RecipeType is the predicate function for recipetype builders.
type RecipeType func(*sql.Selector)
